### ISSUE TITLE
help,me! Why can't I run this demo?

### ISSUE THREAD

**Issue by ameibj** [chitoku-k/homomaid.vue#2]
The error message is:
Uncaught Error: Load timeout for modules: babel!app_unnormalized2,babel!app,babel!router.

I downloaded mian's dependency. The error message is:
Unhandled promise rejection SyntaxError: Unexpected reserved word
    at Function (native)
    at Object.ScriptContext.compile (http://localhost:6300/homomaid.vue/js/libs/copy/httpVueLoader.js:161:17)
    at Object.Component.compile (http://localhost:6300/homomaid.vue/js/libs/copy/httpVueLoader.js:335:44)
    at http://localhost:6300/homomaid.vue/js/libs/copy/httpVueLoader.js:388:38
    at http://localhost:6300/homomaid.vue/js/libs/node_modules/babel-polyfill/dist/polyfill.min.js:2:29463
    at http://localhost:6300/homomaid.vue/js/libs/node_modules/babel-polyfill/dist/polyfill.min.js:2:29572
    at MutationObserver.n.exports.f (http://localhost:6300/homomaid.vue/js/libs/node_modules/babel-polyfill/dist/polyfill.min.js:1:19861)

**Comment by chitoku-k** [comment]
Hi, it seems like you have a dependency which doesn't compile without Babel. Can you show me an example how you load it?
